name: Auto Update Proxies Website

on:
  schedule:
    # Каждую 17-ю минуту каждого часа (18:17, 19:17 …)
    - cron: '17 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Установка библиотек
        run: pip install requests beautifulsoup4

      - name: Запуск парсера
        run: python update_proxies.py

      - name: Сохранение изменений на сайт
        run: |
          git config --global user.name  "GitHub Action"
          git config --global user.email "action@github.com"
          git add index.html last_run.txt
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "Авто-обновление прокси и лога активности" && git push)
